apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-q8lb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kjnl-tenant/rhtap-demo-app/hacbs-test-project-q8lb@sha256:c9d5b142c8e65e98a8262bf63bc170cc62af0045eaf8d3590464faba78154951
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
