apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-q8lb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-q8lb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-q8lb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-q8lb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-q8lb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kjnl-tenant/rhtap-demo-app/hacbs-test-project-q8lb@sha256:c9d5b142c8e65e98a8262bf63bc170cc62af0045eaf8d3590464faba78154951
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
